### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by FlorianHeigl** [joernott/docker-oc-loganalyzer#1]
Hi,

I didn't find out if you already go a more recent base image with a php version above 5.6.
IUS is at php 7.2 but I don't really understood where I could adjust that.
So, unfortunately I'm not able to send you a patch, instead just a reminder that 5.6 is already out of any maintenance and you'll have to do the heavier lifting. :/

**Comment by joernott** [comment]
The web page still states php5 as a requirement. As a result, I based this container on 5.6. I will create a 7.x based spin off but I am afraid that I don't have much time for proper testing.

**Comment by joernott** [comment]
I have switched the master branch to use the apache-php:latest container, which is based on php7. The legacy 5.6 version is tagged php5latest now.

**Comment by FlorianHeigl** [comment]
i'll give it a test run.
